POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RhdXMiLCJpZCI6IjY2NjJkZDhkOWVkODcwYzBmYmU0MTdkZSIsImlhdCI6MTcxNzc1NzE5Nn0.Sq9sA23DVAU9vKP25cTkCRHHXWJU3qYgC3BGueeAhpg


{
  "title": "kolmas",
  "author": "meitsi",
  "url": "testaus13",
  "likes": "2"
}